/*
 * This file is generated by jOOQ.
 */
package stroom.template.set.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.template.set.impl.db.jooq.Indexes;
import stroom.template.set.impl.db.jooq.Keys;
import stroom.template.set.impl.db.jooq.Stroom;
import stroom.template.set.impl.db.jooq.tables.records.TemplateSetRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TemplateSet extends TableImpl<TemplateSetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.template_set</code>
     */
    public static final TemplateSet TEMPLATE_SET = new TemplateSet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TemplateSetRecord> getRecordType() {
        return TemplateSetRecord.class;
    }

    /**
     * The column <code>stroom.template_set.uuid</code>.
     */
    public final TableField<TemplateSetRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>stroom.template_set.set_uuid</code>.
     */
    public final TableField<TemplateSetRecord, String> SET_UUID = createField(DSL.name("set_uuid"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>stroom.template_set.name</code>.
     */
    public final TableField<TemplateSetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.template_set.version</code>.
     */
    public final TableField<TemplateSetRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>stroom.template_set.create_time_ms</code>.
     */
    public final TableField<TemplateSetRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.template_set.update_time_ms</code>.
     */
    public final TableField<TemplateSetRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.template_set.create_user</code>.
     */
    public final TableField<TemplateSetRecord, String> CREATE_USER = createField(DSL.name("create_user"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.template_set.update_user</code>.
     */
    public final TableField<TemplateSetRecord, String> UPDATE_USER = createField(DSL.name("update_user"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.template_set.description</code>.
     */
    public final TableField<TemplateSetRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.template_set.fields</code>.
     */
    public final TableField<TemplateSetRecord, JSON> FIELDS = createField(DSL.name("fields"), SQLDataType.JSON, this, "");

    private TemplateSet(Name alias, Table<TemplateSetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TemplateSet(Name alias, Table<TemplateSetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.template_set</code> table reference
     */
    public TemplateSet(String alias) {
        this(DSL.name(alias), TEMPLATE_SET);
    }

    /**
     * Create an aliased <code>stroom.template_set</code> table reference
     */
    public TemplateSet(Name alias) {
        this(alias, TEMPLATE_SET);
    }

    /**
     * Create a <code>stroom.template_set</code> table reference
     */
    public TemplateSet() {
        this(DSL.name("template_set"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TEMPLATE_SET_IDX_TEMPLATE_SET_SET_UUID);
    }

    @Override
    public UniqueKey<TemplateSetRecord> getPrimaryKey() {
        return Keys.KEY_TEMPLATE_SET_PRIMARY;
    }

    @Override
    public List<UniqueKey<TemplateSetRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_TEMPLATE_SET_UQ_TEMPLATE_SET_UUID);
    }

    @Override
    public TableField<TemplateSetRecord, String> getRecordVersion() {
        return VERSION;
    }

    @Override
    public TemplateSet as(String alias) {
        return new TemplateSet(DSL.name(alias), this);
    }

    @Override
    public TemplateSet as(Name alias) {
        return new TemplateSet(alias, this);
    }

    @Override
    public TemplateSet as(Table<?> alias) {
        return new TemplateSet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TemplateSet rename(String name) {
        return new TemplateSet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TemplateSet rename(Name name) {
        return new TemplateSet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TemplateSet rename(Table<?> name) {
        return new TemplateSet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateSet where(Condition condition) {
        return new TemplateSet(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateSet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateSet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateSet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TemplateSet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TemplateSet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TemplateSet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TemplateSet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateSet whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateSet whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
