/*
 * This file is generated by jOOQ.
 */
package stroom.template.set.impl.db.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import stroom.template.set.impl.db.jooq.tables.TemplateSet;


/**
 * A class modelling indexes of tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TEMPLATE_SET_IDX_TEMPLATE_SET_SET_UUID = Internal.createIndex(DSL.name("idx_template_set_set_uuid"), TemplateSet.TEMPLATE_SET, new OrderField[] { TemplateSet.TEMPLATE_SET.SET_UUID }, false);
}
