/*
 * This file is generated by jOOQ.
 */
package stroom.template.set.impl.db.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import stroom.template.set.impl.db.jooq.tables.TemplateSet;
import stroom.template.set.impl.db.jooq.tables.records.TemplateSetRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TemplateSetRecord> KEY_TEMPLATE_SET_PRIMARY = Internal.createUniqueKey(TemplateSet.TEMPLATE_SET, DSL.name("KEY_template_set_PRIMARY"), new TableField[] { TemplateSet.TEMPLATE_SET.UUID }, true);
}
