/*
 * This file is generated by jOOQ.
 */
package stroom.template.set.impl.db.jooq;


import stroom.template.set.impl.db.jooq.tables.TemplateSet;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>stroom.template_set</code>.
     */
    public static final TemplateSet TEMPLATE_SET = TemplateSet.TEMPLATE_SET;
}
