/*
 * This file is generated by jOOQ.
 */
package stroom.template.set.impl.db.jooq.tables.records;


import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.template.set.impl.db.jooq.tables.TemplateSet;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TemplateSetRecord extends UpdatableRecordImpl<TemplateSetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.template_set.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.template_set.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>stroom.template_set.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.template_set.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stroom.template_set.version</code>.
     */
    public void setVersion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.template_set.version</code>.
     */
    public String getVersion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.template_set.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.template_set.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>stroom.template_set.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.template_set.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>stroom.template_set.create_user</code>.
     */
    public void setCreateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.template_set.create_user</code>.
     */
    public String getCreateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.template_set.update_user</code>.
     */
    public void setUpdateUser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.template_set.update_user</code>.
     */
    public String getUpdateUser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.template_set.description</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.template_set.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.template_set.fields</code>.
     */
    public void setFields(JSON value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.template_set.fields</code>.
     */
    public JSON getFields() {
        return (JSON) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TemplateSetRecord
     */
    public TemplateSetRecord() {
        super(TemplateSet.TEMPLATE_SET);
    }

    /**
     * Create a detached, initialised TemplateSetRecord
     */
    public TemplateSetRecord(String uuid, String name, String version, Long createTimeMs, Long updateTimeMs, String createUser, String updateUser, String description, JSON fields) {
        super(TemplateSet.TEMPLATE_SET);

        setUuid(uuid);
        setName(name);
        setVersion(version);
        setCreateTimeMs(createTimeMs);
        setUpdateTimeMs(updateTimeMs);
        setCreateUser(createUser);
        setUpdateUser(updateUser);
        setDescription(description);
        setFields(fields);
        resetChangedOnNotNull();
    }
}
